import InfoCard from '@/components/Card/InfoCard';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import HomeHeader from '@/components/Welcome/HomeHeader';
import { Box, ListItem, UnorderedList } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" overflow="hidden">
        <Navbar />
        <Box px={{ base: 'full', md: '5%', lg: '15%', xl: '25%' }} mt="61px">
          <Sidebar>
            <HomeHeader
              title={'Welcome to my documentation website!'}
              description={
                "Here, you will find the latest commits and updates of my specific repository and what's new from it. Enjoy!"
              }
              mb={5}
            />
            <InfoCard title={'NEW UPDATED!'}>
              <UnorderedList>
                <ListItem>Add new home header welcoming message</ListItem>
                <ListItem>Add box what's new!</ListItem>
              </UnorderedList>
            </InfoCard>
          </Sidebar>
        </Box>
      </Box>
    </>
  );
}
