import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import { Box } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" overflow="hidden">
        <Navbar />
        <Box px={{ base: 'full', md: '5%', lg: '15%', xl: '25%' }} mt="61px">
          <Sidebar>Log Activity</Sidebar>
        </Box>
      </Box>
    </>
  );
}
